# theme = "everforest_dark"
theme = "nier-automata"

[editor]
mouse = true
bufferline = "multiple"
true-color = true
color-modes = true
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block" # デフォルトで block なので実際には指定する必要はない
select = "underline" 

[keys.insert]
"C-[" = "normal_mode"
