"$schema" = 'https://starship.rs/config-schema.json'

# 空行追加
add_newline = true

# タイムアウト時間
scan_timeout = 10



format = """
$os\
$shell\
$sudo\
$username\
$directory\
$git_branch\
$git_status\
$custom\
$fill\
\n$character
"""

right_format = """
$nodejs\
$rust\
$golang\
$php\
$time\
$cmd_duration\
"""

# $package\


palette = 'nier_colors'


# JIS安全色に則った色設定
[palettes.jis_safe_colors]
jis_red = '#ff4b00'
jis_orange = '#f6aa00'
jis_yellow = '#f2e700'
jis_green = '#00b06b'
jis_blue = '#1971ff'
jis_purple = '#990099'

# カラーユニバーサルデザインに則った色設定
[palettes.cud_colors]
cud_red = '#ff4b00'
cud_yellow = '#f2e700'
cud_green = '#00b06b'
cud_blue = '#1971ff'
cud_sky = '#4dc4ff'
cud_pink = '#ff8078'
cud_orange = '#f6aa00'
cud_purple = '#990099'
cud_brown = '#804000'
cud_light_pink = '#ffcabf'
cud_cream = '#ffff80'
cud_lignt_yellow_green = '#d8f255'
cud_light_sky = '#b4e4ff'
cud_beige ='#ffca80'
cud_light_green = '#77d9a8'
cud_light_purple  = '#c9ace6'
cud_light_gray = '#c8c8cb'
cud_gray = '#84919e'

# ニーア・オートマタのUIデザインを参考にした色設定
[palettes.nier_colors]
nier_beige_dark = '#4e4b42'
nier_beige_semi_dark = '#635f54'
nier_beige_light = '#dad4bb'
nier_beige_semi_light = '#b4af9a'
jis_red = '#ff4b00'
jis_orange = '#f6aa00'
jis_yellow = '#f2e700'
jis_blue = '#1971ff'
jis_purple = '#990099'





# シンボル設定
[character]
success_symbol = "[❯](bold nier_beige_semi_light)[❯](bold nier_beige_semi_dark)[❯](bold nier_beige_dark)"
error_symbol = "[❯](bold jis_red)[❯](bold jis_orange)[❯](bold jis_yellow)"
# success_symbol = "[❯](bold jis_red)[❯](bold jis_orange)[❯](bold jis_yellow)"

[os]
disabled = false
format = """
[](fg:nier_beige_light)\
[ $symbol ]($style)\
[](fg:nier_beige_light)\
"""
style = "bg:nier_beige_light fg:nier_beige_dark"


[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[shell]
disabled = false
style = "bg:nier_beige_light fg:nier_beige_dark"
format = """
[](fg:nier_beige_light)\
[ $indicator]($style)\
[](fg:nier_beige_light)\
"""
bash_indicator = "🦴"
nu_indicator = "》"

[username]
show_always = true
style_user = "bg:nier_beige_light fg:nier_beige_dark"
style_root = "bg:jis_red fg:nier_beige_light"
format = """
[](fg:nier_beige_light)\
[ $user ]($style)\
[](fg:nier_beige_light)\
"""


[sudo]
format = """
[](fg:jis_red)\
[$symbol]($style)\
[](fg:jis_red)\
"""
style = "bg:jis_red fg:nier_beige_light"
symbol = "󰿆 sudo"
disabled = false


[directory]
# style = "bg:nier_beige_dark fg:nier_beige_light"
# format = """
# [](fg:nier_beige_dark)\
# [ $path ]($style)\
# [](fg:nier_beige_dark)\
# """
style = "bg:nier_beige_semi_dark fg:nier_beige_light"
format = """
[](fg:nier_beige_semi_dark)\
[ $path ]($style)\
[](fg:nier_beige_semi_dark)\
"""


truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:nier_beige_dark fg:nier_beige_light"
format = """
[](fg:nier_beige_dark)\
[$symbol $branch]($style)\
[](fg:nier_beige_dark)\
"""

[git_status]
style = "bg:nier_beige_dark fg:nier_beige_light"
format = """
[](fg:nier_beige_dark)\
[$all_status$ahead_behind]($style)\
[](fg:nier_beige_dark)\
"""


# [package]
# format = "via [🎁 $version](208 bold) "

[nodejs]
symbol = ""
style = "bg:nier_beige_semi_dark fg:nier_beige_semi_light"
format = """
[](fg:nier_beige_semi_dark)\
[$symbol ($version)]($style)\
[](fg:nier_beige_semi_dark)\
"""

[rust]
symbol = ""
style = "bg:nier_beige_semi_dark fg:nier_beige_semi_light"
format = """
[](fg:nier_beige_semi_dark)\
[$symbol ($version)]($style)\
[](fg:nier_beige_semi_dark)\
"""

[golang]
symbol = ""
style = "bg:nier_beige_semi_dark fg:nier_beige_semi_light"
format = """
[](fg:nier_beige_semi_dark)\
[$symbol ($version)]($style)\
[](fg:nier_beige_semi_dark)\
"""

[php]
symbol = ""
style = "bg:nier_beige_semi_dark fg:nier_beige_semi_light"
format = """
[](fg:nier_beige_semi_dark)\
[$symbol ($version)]($style)\
[](fg:nier_beige_semi_dark)\
"""

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:nier_beige_semi_dark fg:nier_beige_semi_light"
format = """
[](fg:nier_beige_semi_dark)\
[$time]($style)\
[](fg:nier_beige_semi_dark)\
"""


[cmd_duration]
min_time = 500
style = "bg:nier_beige_semi_dark fg:nier_beige_semi_light"
format = """
[](fg:nier_beige_semi_dark)\
[$duration]($style)\
[](fg:nier_beige_semi_dark)\
"""

[fill]
style = "bg:none fg:nier_beige_semi_light"
symbol = "―"


[custom.no_history_shell]
# when = 'test "$INCOGNITO_SHELL" = 1'
# おそらく，現在のシェルによってこのwhen部分が変わる
# nushellに合わせている
when = "test $env.NO_HISTORY_SHELL == 1"
description = "シェルの隠匿モード（履歴を保存しない）が有効な場合に表示"
symbol = " 󰛑 "
style = "bg:jis_purple fg:nier_beige_light"
format = """
[](fg:jis_purple)\
[$symbol]($style)\
[](fg:jis_purple)\
"""

